services:
  mysql:
    image: mysql:8.0
    container_name: weather-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: weatherdb
      MYSQL_USER: weatheruser
      MYSQL_PASSWORD: weatherpass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: weather-backend
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://weather-mysql:3306/weatherdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: weatheruser
      SPRING_DATASOURCE_PASSWORD: weatherpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: mySecretKey123456789012345678901234567890
      JWT_EXPIRATION: 86400000
      CORS_ALLOWED_ORIGINS: http://localhost:3000
    depends_on:
      mysql:
        condition: service_healthy
    command: ["sh", "-c", "sleep 10 && java -jar app.jar"]

  frontend:
    build:
      context: ./weather-frontend
    container_name: weather-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  mysql_data:
